spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart
    username: root
    password: marcossouza144
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    open-in-view: false

    spring:
      thymeleaf:
        cache: false

        spring:
          jpa:
            properties:
              hibernate:
                show_sql: true
                format_sql: true